In [2]:
import numpy as np

In [4]:
minha_lista = [1,2,3]

In [5]:
minha_lista

[1, 2, 3]

In [7]:
np.array(minha_lista)

array([1, 2, 3])

In [9]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
arr = np.zeros(3)

In [21]:
arr

array([0., 0., 0.])

In [23]:
arr = np.zeros((5,5))

In [25]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
arr = np.ones((3,3))

In [29]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.linspace(0,10,2)

array([ 0., 10.])

In [35]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [37]:
np.random.rand(5)

array([0.02896987, 0.3912875 , 0.04430296, 0.23480242, 0.4568003 ])

In [40]:
np.random.rand(5, 4, 3)

array([[[0.10617866, 0.15661986, 0.20458101],
        [0.25416718, 0.04446829, 0.75284619],
        [0.822302  , 0.21319808, 0.58602626],
        [0.83151337, 0.97296967, 0.34848489]],

       [[0.46597157, 0.30437442, 0.2118794 ],
        [0.01969944, 0.47729123, 0.74387764],
        [0.38017489, 0.42174572, 0.0772634 ],
        [0.25981393, 0.49895827, 0.93832174]],

       [[0.16636987, 0.91368072, 0.17701554],
        [0.8268254 , 0.60170041, 0.88156442],
        [0.44583489, 0.98686065, 0.27135063],
        [0.43711479, 0.92280067, 0.82349716]],

       [[0.64111006, 0.42405572, 0.21309166],
        [0.51538355, 0.40284928, 0.18117968],
        [0.25875726, 0.27739137, 0.88480087],
        [0.94190155, 0.74767891, 0.34924507]],

       [[0.59536193, 0.73561644, 0.75848848],
        [0.9479132 , 0.59749507, 0.06209993],
        [0.22742414, 0.81118016, 0.60719466],
        [0.49997952, 0.20915631, 0.94432527]]])

In [42]:
np.random.randn(4)

array([ 0.33524032,  1.58137387,  0.61162492, -0.18855989])

In [43]:
np.random.randint(0,100,10)

array([56, 21, 83, 96, 18, 68, 72, 67, 50, 76])